eval "$(/opt/homebrew/bin/brew shellenv)"

##
# Your previous /Users/michalruopp/.zprofile file was backed up as /Users/michalruopp/.zprofile.macports-saved_2023-11-25_at_12:11:24
##

# MacPorts Installer addition on 2023-11-25_at_12:11:24: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2023-11-25_at_12:11:24: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.

