# .zshenv
#
# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set the command search path [(i.e. your $PATH)], plus other important environment variables. `.zshenv' should not contain commands that produce output or assume the shell is attached to a tty.
# https://zsh.sourceforge.io/Intro/intro_3.html
#
# Some env vars. Some PATH additions. I think Homebrew needs to do a thing, also.

# default text editor
#   _maybe this section will be expanded to other types of editors and tools, depending on how my workflows evolve._
export EDITOR=nvim

# iCloud
export ICLOUD_DIR="/Users/$USER/Library/Mobile\ Documents/com\~apple\~CloudDocs"

# TODO: also conform to $XDG_CONFIG
__MACHRC_DIR="/Users/$USER/Developer/machrc"
export MACHRC_DIR="$__MACHRC_DIR"
export ZDOTDIR="$__MACHRC_DIR/zsh"

# TODO: move to a "third-party" file
# Homebrew
# NOTE: only for silicon
#eval "$(/opt/homebrew/bin/brew shellenv)"

# TODO: add call to add third-party sources to PATH

#source "$HOME/.cargo/env"
