# zsh/zshrc.zsh
# 
# @desc z-shell run commands, sourced in interactive shells
#
# `.zshrc' is sourced in interactive shells. It should contain commands to set up aliases, functions, options, key bindings, etc.
# https://zsh.sourceforge.io/Intro/intro_3.html

export LSCOLORS=ExFxCxDxBxegedabagacad
#export LS_COLORS="$LS_COLORS:di=0;36:ln=0;93:ex=0;31:"
export LS_COLORS="$LS_COLORS:di=0;34:ln=0;93:ex=0;31:"

. $MACHRC/sh/git.sh

. $MACHRC/zsh/ansi.zsh
. $MACHRC/zsh/aliases.zsh
. $MACHRC/zsh/apparatus.zsh
. $MACHRC/zsh/prompt.zsh
. $MACHRC/zsh/test.zsh
. $MACHRC/zsh/tty.zsh
#. $MACHRC/zsh/web.zsh

# TODO: refactor third-party resources to separate file
# Third-party code
# asdf
# Silicon Homebrew path
#. /opt/homebrew/opt/asdf/libexec/asdf.sh
# asdf
# Intel Homebrew path
. /usr/local/opt/asdf/libexec/asdf.sh

# autojump
# Silicon Homebrew path
# TODO: refactor out the Homebrew path to a reusable variable
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh
