# .zshrc

# Because I always forget this stuff:
# https://zsh.sourceforge.io/Intro/intro_3.html
# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set the command search path [(i.e. your $PATH)], plus other important environment variables. `.zshenv' should not contain commands that produce output or assume the shell is attached to a tty.
# `.zshrc' is sourced in interactive shells. It should contain commands to set up aliases, functions, options, key bindings, etc.
# `.zlogin' is sourced in login shells. It should contain commands that should be executed only in login shells. [`.zlogin' is not the place for alias definitions, options, environment variable settings, etc.; as a general rule, it should not change the shell environment at all. Rather, it should be used to set the terminal type and run a series of external commands (fortune, msgs, etc).] 
# `.zlogout' is sourced when login shells exit. 
# `.zprofile' is similar to `.zlogin', except that it is sourced before `.zshrc'. `.zprofile' is meant as an alternative to `.zlogin' for ksh fans; the two are not intended to be used together, although this could certainly be done if desired.

# zsh stuff
. $MACHRC_DIR/zsh/aliases.zsh
. $MACHRC_DIR/zsh/apparatus.zsh
. $MACHRC_DIR/zsh/prompt.zsh
. $MACHRC_DIR/zsh/test.zsh
. $MACHRC_DIR/zsh/tty.zsh
. $MACHRC_DIR/zsh/web.zsh

# Third-party code
# asdf
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# autojump
#[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh
